### PR TITLE
Update MsgResTonpy.trans

### PR DESCRIPTION
**Pull request by ObiKKa**
Bottom section. One typo correction. I think this phrase here is better?

### CODE REVIEW

**Comment by cjuub** [comment]
Droop is correct (according to its definition), but I guess "hangs" sounds a bit better. I don't think "drop" works.

As for the other one, the previous line ends with "and you touch it...", so "will" in that sentence refers to what happens when after you touched it. So I don't think "can" sounds correct.

**Comment by ObiKKa** [comment]
Ah, righto. I also like the word '[dangle](http://www.thesaurus.com/browse/droop)'. But let's stick with your first choice.
The sentence - perhaps you could move this 'be able to' phrase backwards as a prefix to the two actions of 'grab it' and 'climb it'.

**Comment by cjuub** [comment]
Hm, it still feels a bit wrong. But I agree with you that the original sentence sounds wrong.

How about just:
`Then you will be able to climb it!`

This works with the previously said sentence, and includes your changes making it sound more natural.
(Also note that you need to balance the position of `<N>` to make it fit on screen. http://cjuub.se/u/1604131531207.png )

**Comment by ObiKKa** [comment]
What about 

> Then you will be able to grab on and climb it!

This is short and simplified. Which one do you like better?

**Comment by cjuub** [comment]
The one I said, the reason is that when touching it, you grab it, THEN you **can climb it**. So "be able to grab" does not sound right, as we already know its grabbed.

The whole grab-part is superfluous though, it's enough to say you can climb it.

**Comment by ObiKKa** [comment]
Thanks. Have you noticed this message in my latest commit's text box?

> Does line #758 need a 'you' or 'he', for example in between 'then' and 'won't...'?

**Pull request merged**
