### PR TITLE
Update MsgResGeo.trans

### PR DESCRIPTION
**Pull request by ObiKKa**
Corrected typos. And improved grammar.
Not sure about line #50: 'I'll find you in no time<N> from the air!' If the 'up in' addition in the middle makes sense.

### CODE REVIEW

**Comment by cjuub** [comment]
This is great! Thank you!

But before I merge this:
`That's such a beautiful melody,<N>**that** it has a healing effect.`

This does not work, this makes it sound like Mesa is stating that it is definitively healing. But it is more like she feels that it has a healing effect on her.

Change it too (or something similar):
`That's such a beautiful melody,<N>it feels like it's healing me.`

Again, thanks for finding all these errors!

**Comment by ObiKKa** [comment]
Will this edit work? "That's such a beautiful melody - <N>it feels like it's healing me." So it has a better flow instead of putting a comma in the middle?

**Comment by ObiKKa** [comment]
Or "That's such a beautiful melody...<N>It feels like it's healing me."

**Comment by cjuub** [comment]
Yes, they both work. :)
I prefer the second one.

**Comment by ObiKKa** [comment]
Edited.

**Pull request merged**
